import { defineConfig } from 'astro/config';
import vue from '@astrojs/vue';
import tailwind from '@astrojs/tailwind';
import vercel from '@astrojs/vercel';

// https://astro.build/config
export default defineConfig({
  output: 'server',
  adapter: vercel(),
  integrations: [
    vue(),
    tailwind({
      applyBaseStyles: false,
    })
  ],
  redirects: {
    // Generation pages
    '/c8-corvette-wheels/': '/generations',
    '/c8-stingray/': '/generations/c8/c8-stingray',
    '/c8-z06/': '/generations/c8/c8-z06',
    '/c8-e-ray/': '/generations',
    '/c7-corvette-wheels/': '/generations',
    '/c7-stingray/': '/generations/c7/c7-stingray',
    '/c7-grand-sport/': '/generations/c7/c7-grand-sport',
    '/c7-z06/': '/generations/c7/c7-z06',
    '/c6-corvette-wheels/': '/generations',
    '/c6-grand-sport/': '/generations/c6/c6-grand-sport',
    '/c6-z06/': '/generations',
    '/c5-corvette-wheels/': '/generations',
    '/c5-base-coupe/': '/generations',

    // Wheel series pages
    '/sebring/': '/wheels/sebring',
    '/daytona/': '/wheels/daytona',

    // Product pages - Talladega
    '/product/talladega/': '/shop/single-product?series=Talladega&finish=Brushed Aluminum',
    '/product/rear-21-x-13-20mm-talladega-brushed-aluminum/': '/shop/single-product?series=Talladega&finish=Brushed Aluminum',

    // Product pages - Sonoma
    '/product/sonoma/': '/shop/single-product?series=Sonoma&finish=Brushed Aluminum',

    // Product pages - Sebring
    '/product/sebring/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-2/': '/shop/single-product?series=Sebring&finish=Titanium Gray Brushed',
    '/product/sebring-3/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-4/': '/shop/single-product?series=Sebring&finish=Titanium Brushed',
    '/product/sebring-5/': '/shop/single-product?series=Sebring&finish=Bronze Brushed Tint',
    '/product/sebring-6/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-7/': '/shop/single-product?series=Sebring&finish=Titanium Brushed',
    '/product/sebring-8/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-9/': '/shop/single-product?series=Sebring&finish=Titanium Gray Brushed',
    '/product/sebring-10/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-11/': '/shop/single-product?series=Sebring&finish=Titanium Gray Brushed',
    '/product/sebring-12/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-13/': '/shop/single-product?series=Sebring&finish=Bronze Brushed Tint',
    '/product/sebring-14/': '/shop/single-product?series=Sebring&finish=Titanium Brushed',
    '/product/sebring-15/': '/shop/single-product?series=Sebring&finish=Titanium Brushed',
    '/product/sebring-16/': '/shop/single-product?series=Sebring&finish=Titanium Brushed',
    '/product/sebring-17/': '/shop/single-product?series=Sebring&finish=Titanium Brushed',
    '/product/sebring-18/': '/shop/single-product?series=Sebring&finish=Bronze Brushed Tint',
    '/product/sebring-19/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-20/': '/shop/single-product?series=Sebring&finish=Bronze Brushed Tint',
    '/product/sebring-21/': '/shop/single-product?series=Sebring&finish=Bronze Brushed Tint',
    '/product/sebring-22/': '/shop/single-product?series=Sebring&finish=Chrome',
    '/product/sebring-23/': '/shop/single-product?series=Sebring&finish=Chrome',
    '/product/sebring-24/': '/shop/single-product?series=Sebring&finish=Chrome',
    '/product/sebring-25/': '/shop/single-product?series=Sebring&finish=Chrome',
    '/product/sebring-gblk/': '/shop/single-product?series=Sebring&finish=Gloss Black',
    '/product/sebring-brz/': '/shop/single-product?series=Sebring&finish=Bronze Brushed Tint',
    '/product/sebring-tiu/': '/shop/single-product?series=Sebring&finish=Titanium Gray Brushed',

    // Product pages - Daytona
    '/product/daytona/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-2/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',
    '/product/daytona-3/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-4/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',
    '/product/daytona-5/': '/shop/single-product?series=Daytona&finish=Bronze Brushed Tint',
    '/product/daytona-6/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-7/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',
    '/product/daytona-8/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-9/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',
    '/product/daytona-10/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-11/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',
    '/product/daytona-12/': '/shop/single-product?series=Daytona&finish=Bronze Brushed Tint',
    '/product/daytona-13/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-14/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',
    '/product/daytona-15/': '/shop/single-product?series=Daytona&finish=Bronze Brushed Tint',
    '/product/daytona-16/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-17/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',
    '/product/daytona-18/': '/shop/single-product?series=Daytona&finish=Bronze Brushed Tint',
    '/product/daytona-19/': '/shop/single-product?series=Daytona&finish=Bronze Brushed Tint',
    '/product/daytona-20/': '/shop/single-product?series=Daytona&finish=Chrome',
    '/product/daytona-21/': '/shop/single-product?series=Daytona&finish=Chrome',
    '/product/daytona-22/': '/shop/single-product?series=Daytona&finish=Chrome',
    '/product/daytona-23/': '/shop/single-product?series=Daytona&finish=Chrome',
    '/product/daytona-24/': '/shop/single-product?series=Daytona&finish=Titanium Gray Brushed',
    '/product/daytona-25/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-26/': '/shop/single-product?series=Daytona&finish=Bronze Brushed Tint',
    '/product/daytona-gblk/': '/shop/single-product?series=Daytona&finish=Gloss Black',
    '/product/daytona-brz/': '/shop/single-product?series=Daytona&finish=Bronze Brushed Tint',
    '/product/daytona-tiu/': '/shop/single-product?series=Daytona&finish=Titanium Brushed',

    // Product pages - Speedway
    '/product/speedway/': '/shop/single-product?series=Speedway&finish=Gloss Black',
    '/product/speedway-2/': '/shop/single-product?series=Speedway&finish=Gloss Black',
    '/product/speedway-3/': '/shop/single-product?series=Speedway&finish=Chrome',
    '/product/speedway-4/': '/shop/single-product?series=Speedway&finish=Dark Bronze',
    '/product/speedway-5/': '/shop/single-product?series=Speedway&finish=Titanium Brushed',
    '/product/speedway-6/': '/shop/single-product?series=Speedway&finish=Gloss Black',
    '/product/speedway-7/': '/shop/single-product?series=Speedway&finish=Dark Bronze',
    '/product/speedway-8/': '/shop/single-product?series=Speedway&finish=Titanium Brushed',
    '/product/speedway-9/': '/shop/single-product?series=Speedway&finish=Dark Bronze',
    '/product/speedway-10/': '/shop/single-product?series=Speedway&finish=Titanium Brushed Tint',
    '/product/speedway-11/': '/shop/single-product?series=Speedway&finish=Chrome',
    '/product/speedway-12/': '/shop/single-product?series=Speedway&finish=Gloss Black',
    '/product/speedway-13/': '/shop/single-product?series=Speedway&finish=Titanium Brushed',
    '/product/speedway-14/': '/shop/single-product?series=Speedway&finish=Dark Bronze',
    '/product/speedway-15/': '/shop/single-product?series=Speedway&finish=Chrome',
    '/product/speedway-gloss-black/': '/shop/single-product?series=Speedway&finish=Gloss Black',
    '/product/speedway-titanium-brushed/': '/shop/single-product?series=Speedway&finish=Titanium Brushed',
    '/product/speedway-bronze-brushed-tint/': '/shop/single-product?series=Speedway&finish=Dark Bronze',

    // Other pages
    '/catalog-2025/': '/catalog',
    '/become-a-dealer/': '/vendor-registration',
    '/gallery/': '/gallery/vehicles',
    '/spun-forged-technology/': '/process',
    '/racing/': '/wheels',
    '/downloads/': '/media',

    // Year/Model-specific pages - C8 Stingray
    '/custom-wheels-for-my-2024-c8-corvette-stingray/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2023-c8-corvette-stingray/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2022-c8-corvette-stingray/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2021-c8-corvette-stingray/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2020-c8-corvette-stingray/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2023-chevrolet-corvette-stingray-coupe/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2023-chevrolet-corvette-stingray-convertible/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2022-chevrolet-corvette-stingray-coupe/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2022-chevrolet-corvette-stingray-convertible/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2021-chevrolet-corvette-stingray/': '/generations/c8/c8-stingray',
    '/custom-wheels-for-my-2020-chevrolet-corvette-stingray/': '/generations/c8/c8-stingray',

    // Year/Model-specific pages - C7 Stingray
    '/custom-wheels-for-my-2019-c7-corvette-stingray/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2019-c7-corvette-z51/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2017-c7-corvette-stingray/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2014-c7-corvette-stingray/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2019-chevrolet-corvette-stingray-coupe/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2019-chevrolet-corvette-stingray-convertible/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2018-chevrolet-corvette-stingray-coupe/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2018-chevrolet-corvette-stingray-convertible/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2018-chevrolet-corvette-stingray/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2017-chevrolet-corvette-stingray-coupe/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2017-chevrolet-corvette-stingray-convertible/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2016-chevrolet-corvette-stingray-coupe/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2016-chevrolet-corvette-stingray-convertible/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2015-chevrolet-corvette-stingray-coupe/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2015-chevrolet-corvette-stingray-convertible/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2014-chevrolet-corvette-stingray-coupe/': '/generations/c7/c7-stingray',
    '/custom-wheels-for-my-2014-chevrolet-corvette-stingray-convertible/': '/generations/c7/c7-stingray',

    // Year/Model-specific pages - C7 Z06
    '/custom-wheels-for-my-2017-c7-corvette-z06/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2016-c7-corvette-z06/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2015-c7-stingray-z06/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2019-chevrolet-corvette-z06-coupe/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2019-chevrolet-corvette-z06-convertible/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2018-chevrolet-corvette-z06-coupe/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2018-chevrolet-corvette-z06-convertible/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2017-chevrolet-corvette-z06-coupe/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2017-chevrolet-corvette-z06-convertible/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2016-chevrolet-corvette-z06-coupe/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2016-chevrolet-corvette-z06-convertible/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2015-chevrolet-corvette-z06-coupe/': '/generations/c7/c7-z06',
    '/custom-wheels-for-my-2015-chevrolet-corvette-z06-convertible/': '/generations/c7/c7-z06',

    // Year/Model-specific pages - C7 Grand Sport
    '/custom-wheels-for-my-2019-chevrolet-corvette-grand-sport-coupe/': '/generations/c7/c7-grand-sport',
    '/custom-wheels-for-my-2019-chevrolet-corvette-grand-sport-convertible/': '/generations/c7/c7-grand-sport',
    '/custom-wheels-for-my-2018-chevrolet-corvette-grand-sport-coupe/': '/generations/c7/c7-grand-sport',
    '/custom-wheels-for-my-2018-chevrolet-corvette-grand-sport-convertible/': '/generations/c7/c7-grand-sport',
    '/custom-wheels-for-my-2017-chevrolet-corvette-grand-sport-coupe/': '/generations/c7/c7-grand-sport',
    '/custom-wheels-for-my-2017-chevrolet-corvette-grand-sport-convertible/': '/generations/c7/c7-grand-sport',

    // Year/Model-specific pages - C6 Grand Sport
    '/custom-wheels-for-my-2013-chevrolet-corvette-grand-sport-hatchback/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2013-chevrolet-corvette-grand-sport-convertible/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2012-chevrolet-corvette-grand-sport-hatchback/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2012-chevrolet-corvette-grand-sport-convertible/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2012-c6-corvette-grand-sport/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2011-chevrolet-corvette-grand-sport-hatchback/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2011-chevrolet-corvette-grand-sport-convertible/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2010-chevrolet-corvette-grand-sport-hatchback/': '/generations/c6/c6-grand-sport',
    '/custom-wheels-for-my-2010-chevrolet-corvette-grand-sport-convertible/': '/generations/c6/c6-grand-sport',

    // Year/Model-specific pages - Other variants to /generations
    '/custom-wheels-for-my-2022-corvette-c8-r/': '/generations',
    '/custom-wheels-for-my-2019-chevrolet-corvette-zr1-coupe/': '/generations',
    '/custom-wheels-for-my-2019-chevrolet-corvette-zr1-convertible/': '/generations',
    '/custom-wheels-for-my-2013-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2013-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2013-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2013-chevrolet-corvette-zr1-hatchback/': '/generations',
    '/custom-wheels-for-my-2013-chevrolet-corvette-427-convertible/': '/generations',
    '/custom-wheels-for-my-2012-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2012-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2012-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2012-chevrolet-corvette-zr1-hatchback/': '/generations',
    '/custom-wheels-for-my-2011-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2011-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2011-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2011-chevrolet-corvette-z06-carbon-hatchback/': '/generations',
    '/custom-wheels-for-my-2011-chevrolet-corvette-zr1-hatchback/': '/generations',
    '/custom-wheels-for-my-2010-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2010-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2010-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2010-chevrolet-corvette-zr1-hatchback/': '/generations',
    '/custom-wheels-for-my-2009-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2009-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2009-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2009-chevrolet-corvette-zr1-hatchback/': '/generations',
    '/custom-wheels-for-my-2008-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2008-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2008-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2008-corvette-c6-base/': '/generations',
    '/custom-wheels-for-my-2008-corvette-c6-z06/': '/generations',
    '/custom-wheels-for-my-2008-chevrolet-corvette-427-limited-edition-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2007-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2007-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2007-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2007-c6-z06/': '/generations',
    '/custom-wheels-for-my-2006-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2006-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2006-chevrolet-corvette-z06-hatchback/': '/generations',
    '/custom-wheels-for-my-2005-chevrolet-corvette-base-hatchback/': '/generations',
    '/custom-wheels-for-my-2005-chevrolet-corvette-base-convertible/': '/generations',
    '/custom-wheels-for-my-2005-c6-corvette/': '/generations',
  },
  server: {
    port: 8080
  },
  vite: {
    resolve: {
      alias: {
        '@': '/src'
      }
    }
  }
});
