export interface GalleryMediaItem {
  type: 'image' | 'video';
  url?: string;
  youtubeId?: string;
  thumbnail?: string;
}

export interface CorvetteGalleryItem {
  galleryId: string | null;
  year: string | null;
  submodel: string | null;
  trim: string | null;
  vehicleColor: string | null;
  vehicleTitle: string | null;
  wheelStyle: string | null;
  wheelFinish: string | null;
  wheelSizeF: string | null;
  offesetF: string | null;
  partF: string | null;
  tireSizeF: string | null;
  tirePartF: string | null;
  wheelSizeRear: string | null;
  offsetR: string | null;
  wheelPartR: string | null;
  tireSizeR: string | null;
  tirePartR: string | null;
  tireModel: string | null;
  images?: string[];
  media?: GalleryMediaItem[];
  pinned?: boolean;
  dateAdded?: string;
}

export const corvetteGalleryData: CorvetteGalleryItem[] = [
  {
    "galleryId": "2026-corvette-e-ray-blue-with-sebring-2p-bronze-black-lip-wheels",
    "dateAdded": "2026-05-23",
    "year": "2026",
    "submodel": "C8",
    "trim": "E-Ray",
    "vehicleColor": "Blue",
    "vehicleTitle": "2026 C8 Corvette E-Ray Blue",
    "wheelStyle": "Sebring 2P",
    "wheelFinish": "Bronze Black Lip",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": null,
    "partF": "E5SE2P201003",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": null,
    "wheelPartR": "E5SE2P211303",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "pinned": false,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp"]
  },
  {
    "galleryId": "2025-c8-z06-black-with-sebring-2p-bronze-polished-lip-wheels",
    "dateAdded": "2026-05-16",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": "Black",
    "vehicleTitle": "2025 C8 Corvette Z06 Black",
    "wheelStyle": "Sebring 2P",
    "wheelFinish": "Bronze Polished Lip",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5SE2P201012",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5SE2P211312",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp"]
  },
  {
    "galleryId": "2025-c8-stingray-70th-white-with-e5-daytona-titanium-brushed-wheels",
    "dateAdded": "2026-05-16",
    "year": "2025",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": "White",
    "vehicleTitle": "2025 C8 Corvette Stingray 70th Anniversary White",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA2090E35520TIU",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5DA2112E52520TIU",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp","29.webp","30.webp","31.webp","32.webp","33.webp","34.webp","35.webp","36.webp","37.webp","38.webp","39.webp","40.webp","41.webp","42.webp","43.webp","44.webp","45.webp","46.webp"]
  },
  {
    "galleryId": "2026-c8-z06-white-with-e5-sebring-2p-gray-polished-lip-wheels",
    "dateAdded": "2026-05-16",
    "year": "2026",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": "White",
    "vehicleTitle": "2026 C8 Corvette Z06 White",
    "wheelStyle": "Sebring 2P",
    "wheelFinish": "Gray Polished Lip",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5SE2P201008",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5SE2P211308",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp"]
  },
  {
    "galleryId": "2018-c7-z06-white-with-e5-daytona-titanium-brushed-tint-wheels",
    "dateAdded": "2026-05-16",
    "year": "2018",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": "White",
    "vehicleTitle": "2018 C7 Corvette Z06 White",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565TIU",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565TIU",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp"]
  },
  {
    "galleryId": "2016-c7-z06-white-with-e5-daytona-gloss-black-wheels",
    "dateAdded": "2026-05-16",
    "year": "2016",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": "White",
    "vehicleTitle": "2016 C7 Corvette Z06 White",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565BK",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565BK",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp"]
  },
  {
    "galleryId": "2018-c7-grand-sport-black-with-e5-daytona-bronze-brushed-tint-wheels",
    "dateAdded": "2026-05-16",
    "year": "2018",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": "Black",
    "vehicleTitle": "2018 C7 Corvette Grand Sport Black",
    "wheelStyle": "Daytona",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565BBT",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565BBT",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp","29.webp","30.webp","31.webp","32.webp","33.webp","34.webp","35.webp","36.webp","37.webp","38.webp","39.webp","40.webp","41.webp","42.webp","43.webp","44.webp","45.webp","46.webp","47.webp"]
  },
  {
    "galleryId": "2026-c8-z06-white-with-e5-sonoma-brushed-aluminum-wheels",
    "dateAdded": "2026-05-15",
    "year": "2026",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": "White",
    "vehicleTitle": "2026 C8 Corvette Z06 White",
    "wheelStyle": "Sonoma",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5SO2010E25520AB",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5SO2113E20520AB",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp"]
  },
  {
    "galleryId": "2026-c8-z06-black-and-white-duo-with-sonoma-brushed-silver-wheels",
    "dateAdded": "2026-05-15",
    "year": "2026",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": "Black and White",
    "vehicleTitle": "2026 C8 Corvette Z06 Black & White Duo",
    "wheelStyle": "Sonoma",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5SO2010E25520AB",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5SO2113E20520AB",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp"]
  },
  {
    "galleryId": "2026-c8-zr1-with-e5-talladega-brushed-silver-wheels-night-shot",
    "dateAdded": "2026-05-15",
    "year": "2026",
    "submodel": "C8",
    "trim": "ZR1",
    "vehicleColor": "White",
    "vehicleTitle": "2026 C8 Corvette ZR1 White",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5TA2113E20520AB",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp"]
  },
  {
    "galleryId": "2026-c8-z06-white-with-sonoma-brushed-silver-wheels-night-shot",
    "dateAdded": "2026-05-14",
    "year": "2026",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": "White",
    "vehicleTitle": "2026 C8 Corvette Z06 White",
    "wheelStyle": "Sonoma",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5SO2010E25520AB",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5SO2113E20520AB",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp"]
  },
  {
    "galleryId": "2025-c8-z06-black-with-talladega-brushed-silver-wheels",
    "dateAdded": "2026-05-14",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": "Black",
    "vehicleTitle": "2025 C8 Corvette Z06 Black",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5TA2113E20520AB",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp","29.webp","30.webp","31.webp","32.webp"]
  },
  {
    "galleryId": "2025-c8-corvette-stingray-white-with-sebring-2p",
    "year": "2025",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": "White",
    "vehicleTitle": "2025 C8 Corvette Stingray White",
    "wheelStyle": "Sebring 2P",
    "wheelFinish": "Titanium Black Lip",
    "pinned": true,
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "+35mm",
    "partF": "E5SE2P1902",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "+45mm",
    "wheelPartR": "E5SE2P201102",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp"]
  },
  {
    "galleryId": "2006-c6-stingray",
    "year": "2006",
    "submodel": "C6",
    "trim": "Base",
    "vehicleColor": "Matte Black",
    "vehicleTitle": "2006 C6 Corvette",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 9.5\"",
    "offesetF": "53mm",
    "partF": "E5SE1995E53565BK",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "76mm",
    "wheelPartR": "E5SE2011E76565BK",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp"]
  },
  {
    "galleryId": "2012-corvette-c6",
    "year": "2012",
    "submodel": "C6",
    "trim": "Base",
    "vehicleColor": null,
    "vehicleTitle": "2012 C6 Corvette",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9.5\"",
    "offesetF": "53mm",
    "partF": "E5DA1995E53565TIU",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "76mm",
    "wheelPartR": "E5DA2011E76565TIU",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp"]
  },
  {
    "galleryId": "2012-c6-corvette",
    "year": "2012",
    "submodel": "C6",
    "trim": "Base",
    "vehicleColor": null,
    "vehicleTitle": "2012 C6 Corvette",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9.5\"",
    "offesetF": "53mm",
    "partF": "E5DA1995E53565TIU",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "76mm",
    "wheelPartR": "E5DA2011E76565TIU",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp"]
  },
  {
    "galleryId": "c6-2012-grand-sport",
    "year": "2012",
    "submodel": "C6",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2012 C6 Corvette Grand Sport",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565TIU",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565TIU",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp"]
  },
  {
    "galleryId": "2014-stingray-z51",
    "year": "2014",
    "submodel": "C7",
    "trim": null,
    "vehicleColor": null,
    "vehicleTitle": "2014 C7 Corvette",
    "wheelStyle": "Daytona",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "19\" x 9.5\"",
    "offesetF": "53mm",
    "partF": "E5DA1995E53565BBT",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "76mm",
    "wheelPartR": "E5DA2011E76565BBT",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp"]
  },
  {
    "galleryId": "c7-white",
    "year": "2015",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2015 C7 Corvette Z06 Laguna Blue",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565BK",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": "Continental ExtremeContact Sport 02",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp"]
  },
  {
    "galleryId": "2015-c7-z06-laguna-blue",
    "year": "2015",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": "Laguna Blue",
    "vehicleTitle": "2015 C7 Corvette Z06 Laguna Blue",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565BK",
    "tireSizeF": "285/30R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": "Continental ExtremeContact Sport 2",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp"]
  },
  {
    "galleryId": "2016-corvette-c7-z06-white",
    "year": "2016",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2016 C7 Corvette Z06",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565BK",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "tQQGmKG4i78", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" }
    ]
  },
  {
    "galleryId": "2016-c7-corvette-z06",
    "year": "2016",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2016 C7 Corvette Z06",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565TIU",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565TIU",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "ky69HgmLFH8", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" }
    ]
  },
  {
    "galleryId": "c7-z06-sebring",
    "year": "2017",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2017 C7 Corvette Grand Sport",
    "wheelStyle": "Sebring",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565TIU",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565TIU",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": "Continental Sport 02",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp"]
  },
  {
    "galleryId": "2017-c7-grand-sport-long-beach-metallic-red",
    "year": "2017",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2017 C7 Corvette Grand Sport",
    "wheelStyle": "Daytona",
    "wheelFinish": "Chrome",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565CH",
    "tireSizeF": "275/30R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565CH",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": "Continental ExtremeContact Sport 02",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp"]
  },
  {
    "galleryId": "2017-c7-grand-sport-2",
    "year": "2017",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2017 C7 Corvette Grand Sport",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565BK",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "zaj3XzLPxdk", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" }
    ]
  },
  {
    "galleryId": "2017-c7-grand-sport",
    "year": "2017",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2017 C7 Corvette Grand Sport Collectors Edition",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565BK",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp"]
  },
  {
    "galleryId": "2017-c7-stingray",
    "year": "2017",
    "submodel": "C7",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2017 C7 Corvette Stingray",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 9.5\"",
    "offesetF": "53mm",
    "partF": "E5DA1995E53565BK",
    "tireSizeF": "275/30R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "76mm",
    "wheelPartR": "E5DA2011E76565BK",
    "tireSizeR": "325/25R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp"]
  },
  {
    "galleryId": "2017-c7-z06-racing-yellow",
    "year": "2017",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2017 C7 Corvette Z06 Racing Yellow",
    "wheelStyle": "Sebring",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565TIU",
    "tireSizeF": "275/30R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565TIU",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": "Continental ExtremeContact Sport 02",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp"]
  },
  {
    "galleryId": "2018-c7-corvette-grand-sport",
    "year": "2018",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2018 C7 Corvette Grand Sport",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565BK",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "tQQGmKG4i78", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" }
    ]
  },
  {
    "galleryId": "2019-c7-grand-sport",
    "year": "2019",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2019 C7 Corvette Grand Sport",
    "wheelStyle": "Sebring",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565TIU",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565TIU",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp"]
  },
  {
    "galleryId": "c7-orange-grand-sport",
    "year": "2019",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2019 C7 Corvette Grand Sport Sebring Orange",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5DA1910E30565TIU",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5DA2012E50565TIU",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": "Continental ExtremeContact Sport 02",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp"]
  },
  {
    "galleryId": "2019-c7-z51",
    "year": "2019",
    "submodel": "C7",
    "trim": "Z51",
    "vehicleColor": null,
    "vehicleTitle": "2019 C7 Corvette Z51",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 9.5\"",
    "offesetF": "53mm",
    "partF": "E5DA1995E53565BK",
    "tireSizeF": "275/30R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "76mm",
    "wheelPartR": "E5DA2011E76565BK",
    "tireSizeR": "325/25R20",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp"]
  },
  {
    "galleryId": "2019-c7-grand-sport-2",
    "year": "2019",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": null,
    "vehicleTitle": "2019 C7 Grand Sport",
    "wheelStyle": "Speedway",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SP1910E30565BK",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SP2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "eZ8RoPZG6Yo", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" }
    ]
  },
  {
    "galleryId": "2019-c7-z06",
    "year": "2019",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2019 C7 Z06",
    "wheelStyle": "Sebring",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565BBT",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565BBT",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp","29.webp","30.webp","31.webp","32.webp","33.webp","34.webp","35.webp","36.webp","37.webp","38.webp","39.webp","40.webp","41.webp","42.webp","43.webp","44.webp","45.webp"],
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "_CoABjEOzek", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" },
      { "type": "image", "url": "20.webp" },
      { "type": "image", "url": "21.webp" },
      { "type": "image", "url": "22.webp" },
      { "type": "image", "url": "23.webp" },
      { "type": "image", "url": "24.webp" },
      { "type": "image", "url": "25.webp" },
      { "type": "image", "url": "26.webp" },
      { "type": "image", "url": "27.webp" },
      { "type": "image", "url": "28.webp" },
      { "type": "image", "url": "29.webp" },
      { "type": "image", "url": "30.webp" },
      { "type": "image", "url": "31.webp" },
      { "type": "image", "url": "32.webp" },
      { "type": "image", "url": "33.webp" },
      { "type": "image", "url": "34.webp" },
      { "type": "image", "url": "35.webp" },
      { "type": "image", "url": "36.webp" },
      { "type": "image", "url": "37.webp" },
      { "type": "image", "url": "38.webp" },
      { "type": "image", "url": "39.webp" },
      { "type": "image", "url": "40.webp" },
      { "type": "image", "url": "41.webp" },
      { "type": "image", "url": "42.webp" },
      { "type": "image", "url": "43.webp" },
      { "type": "image", "url": "44.webp" },
      { "type": "image", "url": "45.webp" }
    ]
  },
  {
    "galleryId": "2019-c7-z06-purple",
    "year": "2019",
    "submodel": "C7",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2019 Custom Widebody C7 Corvette Z06",
    "wheelStyle": "Sebring",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565BBT",
    "tireSizeF": "275/30R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565BBT",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": "Continental ExtremeContact Sport 02",
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "9XkHRCzutcQ", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" }
    ]
  },
  {
    "galleryId": "2020-c8-70th-anniversary-edition",
    "year": "2020",
    "submodel": "C8",
    "trim": null,
    "vehicleColor": null,
    "vehicleTitle": "2020 C8 Corvette 70th Anniversary Edition",
    "wheelStyle": "Sebring",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE1990E35520BBT",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5SE2011E45520BBT",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Pirelli",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp"]
  },
  {
    "galleryId": "c8-2022-yellow-stingray-c8r",
    "year": "2022",
    "submodel": "C8",
    "trim": "C8.R",
    "vehicleColor": null,
    "vehicleTitle": "2022 C8 Corvette C8.R Special Edition Accelerate Yellow",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA1990E35520BK",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5DA2011E45520BK",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp"]
  },
  {
    "galleryId": "2023-c8-corvette-stingray-blue",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 C8 Corvette Stingray",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA1990E35520TIU",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5DA2011E45520TIU",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Toyo Proxy R888R",
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "LEi6lorr5PA", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" },
      { "type": "image", "url": "20.webp" },
      { "type": "image", "url": "21.webp" },
      { "type": "image", "url": "22.webp" },
      { "type": "image", "url": "23.webp" },
      { "type": "image", "url": "24.webp" },
      { "type": "image", "url": "25.webp" },
      { "type": "image", "url": "26.webp" },
      { "type": "image", "url": "27.webp" }
    ]
  },
  {
    "galleryId": "2023-c8-stingray-3lt",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 C8 Corvette Stingray 3LT",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA1990E35520TIU",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5DA2011E45520TIU",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Toyo Proxy R888R",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp"]
  },
  {
    "galleryId": "2023-c8-stingray-torch-red",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 C8 Stingray Torch Red",
    "wheelStyle": "Sebring",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE2090E35520TIU",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SE2112E52520TIU",
    "tireSizeR": "355/30R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp"]
  },
  {
    "galleryId": "2023-c8-stingray-daytona",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA1990E35520TIU",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5DA2011E45520TIU",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Toyo Proxy R888R",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp"]
  },
  {
    "galleryId": "c8-stingray-black-sebring",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray Black",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE2090E35520BK",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SE2112E52520BK",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp"]
  },
  {
    "galleryId": "2023-c8-green-stingray",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray Hypersonic Gray Metallic",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA1990E35520TIU",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5DA2011E45520TIU",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp"]
  },
  {
    "galleryId": "2023-c8-corvette-rapid-blue",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray Rapid Blue",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE1990E35520BK",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5SE2011E45520BK",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Pirelli",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp"]
  },
  {
    "galleryId": "2023-corvette-c8-stingray-torch-red-daytona",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray Torch Red",
    "wheelStyle": "Daytona",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA1990E35520TIU",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5DA2011E45520TIU",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp"]
  },
  {
    "galleryId": "2023-corvette-c8-stingray-torch-red-sebring",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray Torch Red",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE2090E35520BK",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SE2112E52520BK",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp"]
  },
  {
    "galleryId": "red-corvette-c8-speedway-titanium-brushed",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray Torch Red",
    "wheelStyle": "Speedway",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SP2090E35520TIU",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SP2112E52520TIU",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp"]
  },
  {
    "galleryId": "2023-c8-z51-arctic-white-speedway",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Stingray Z51 Arctic White",
    "wheelStyle": "Speedway",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SP1990E35520TIU",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5SP2011E45520TIU",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp"]
  },
  {
    "galleryId": "2023-c8-z51-arctic-white",
    "year": "2023",
    "submodel": "C8",
    "trim": "Z51",
    "vehicleColor": null,
    "vehicleTitle": "2023 Corvette C8 Z51 Arctic White",
    "wheelStyle": "Sebring",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE2090E35520BBT",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SE2112E52520BBT",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp"]
  },
  {
    "galleryId": "2024-c8-anderson-composite-kit",
    "year": "2024",
    "submodel": "C8",
    "trim": null,
    "vehicleColor": null,
    "vehicleTitle": "2024 C8 Anderson Composite Kit",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA2090E35520BK",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5DA2112E52520BK",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp"]
  },
  {
    "galleryId": "2024-c8-corvette-stingray",
    "year": "2024",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2024 C8 Corvette Stingray",
    "wheelStyle": "Daytona",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5DA1990E35520BBT",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5DA2011E45520BBT",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp","29.webp","30.webp"]
  },
  {
    "galleryId": "2024-c8-corvette-stingray-2",
    "year": "2024",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2024 C8 Corvette Stingray",
    "wheelStyle": "Speedway",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SP1990E35520TIU",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5SP2011E45520TIU",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Pirelli",
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "SBPJihKD9PQ", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" },
      { "type": "image", "url": "20.webp" },
      { "type": "image", "url": "21.webp" },
      { "type": "image", "url": "22.webp" }
    ]
  },
  {
    "galleryId": "2024-c8-corvette-z06",
    "year": "2024",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2024 C8 Corvette Z06",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": "275/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20",
    "wheelPartR": "E5TA2113E20520AB",
    "tireSizeR": "345/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "qXNLtY001zk", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" }
    ]
  },
  {
    "galleryId": "2024-c8-stingray",
    "year": "2024",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2024 C8 Stingray",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE2090E35520BK",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SE2112E52520BK",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp"]
  },
  {
    "galleryId": "2024-c8-stingray-accelerate-yellow",
    "year": "2024",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2024 C8 Stingray Accelerate yellow",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE1990E35520BK",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": null,
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp"]
  },
  {
    "galleryId": "2024-c8-stingray-torch-red",
    "year": "2024",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2024 C8 Stingray Torch Red",
    "wheelStyle": "Sebring",
    "wheelFinish": "Bronze Brushed Tint",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE1990E35520BBT",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5SE2011E45520BBT",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp"]
  },
  {
    "galleryId": "2024-chevrolet-c8-3lt",
    "year": "2024",
    "submodel": "C8",
    "trim": "3LT",
    "vehicleColor": null,
    "vehicleTitle": "2024 Chevrolet C8 Stingray 3LT",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE2090E35520BK",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SE2112E52520BK",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp"]
  },
  {
    "galleryId": "2025-c8-corvette-z06-blessing-farms",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2025 C8 Corvette Z06 – Blessing Farms",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": "275/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": null,
    "tireSizeR": "345/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp"]
  },
  {
    "galleryId": "2025-c8-corvette-z06-cathedral",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2025 C8 Corvette Z06 – Cathedral",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": "275/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": null,
    "tireSizeR": "345/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp"]
  },
  {
    "galleryId": "2025-c8-corvette-z06-downtown",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2025 C8 Corvette Z06 – Downtown",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": "275/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": null,
    "tireSizeR": "345/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "Fu5qqPtfnx0", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" }
    ]
  },
  {
    "galleryId": "2025-c8-corvette-zr1",
    "year": "2025",
    "submodel": "C8",
    "trim": "ZR1",
    "vehicleColor": "White",
    "vehicleTitle": "2025 C8 Corvette ZR1",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": "275/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": null,
    "tireSizeR": "345/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "WyYxPUnEpbg", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" },
      { "type": "image", "url": "20.webp" },
      { "type": "image", "url": "21.webp" },
      { "type": "image", "url": "22.webp" },
      { "type": "image", "url": "23.webp" },
      { "type": "image", "url": "24.webp" },
      { "type": "image", "url": "25.webp" },
      { "type": "image", "url": "26.webp" },
      { "type": "image", "url": "27.webp" }
    ]
  },
  {
    "galleryId": "2025-c8-stingray",
    "year": "2025",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "2025 C8 Stingray",
    "wheelStyle": "Speedway",
    "wheelFinish": "Dark Bronze",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SP1990E35520DB",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5SP2011E45520DB",
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Toyo Proxy R888R",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp"]
  },
  {
    "galleryId": "2025-c8-z06",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2025 C8 Z06",
    "wheelStyle": "Talladega",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520AB",
    "tireSizeF": "275/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": null,
    "tireSizeR": "345/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "_k8FLM-oF0k", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" },
      { "type": "image", "url": "20.webp" },
      { "type": "image", "url": "21.webp" },
      { "type": "image", "url": "22.webp" }
    ]
  },
  {
    "galleryId": "c8-z06-with-sonoma-wheels-e5",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2025 C8 Z06 Black",
    "wheelStyle": "Sonoma",
    "wheelFinish": "Brushed Aluminum",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25MM",
    "partF": "E5SO2010E25520AB",
    "tireSizeF": "275/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20MM",
    "wheelPartR": "E5SO2113E20520AB",
    "tireSizeR": "345/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp"],
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "RR7pRpKJUBU", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" },
      { "type": "image", "url": "20.webp" },
      { "type": "image", "url": "21.webp" },
      { "type": "image", "url": "22.webp" },
      { "type": "image", "url": "23.webp" },
      { "type": "image", "url": "24.webp" },
      { "type": "image", "url": "25.webp" },
      { "type": "image", "url": "26.webp" },
      { "type": "image", "url": "27.webp" },
      { "type": "image", "url": "28.webp" }
    ]
  },
  {
    "galleryId": "c6-grand-sport",
    "year": "2015",
    "submodel": "C6",
    "trim": "Grand Sport",
    "vehicleColor": "Burgandy",
    "vehicleTitle": "C6 Grand Sport",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SE1910E30565BK",
    "tireSizeF": "285/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SE2012E50565BK",
    "tireSizeR": "335/25R20",
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp"]
  },
  {
    "galleryId": "c7-speedway-titanium-brushed",
    "year": "2015",
    "submodel": "C7",
    "trim": "Grand Sport",
    "vehicleColor": "Orange",
    "vehicleTitle": "2015 C7 Grand Sport Orange",
    "wheelStyle": "Speedway",
    "wheelFinish": "Titanium Brushed",
    "wheelSizeF": "19\" x 10\"",
    "offesetF": "30mm",
    "partF": "E5SP1910E30565TIU",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 12\"",
    "offsetR": "50mm",
    "wheelPartR": "E5SP2012E50565TIU",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "media": [
      { "type": "image", "url": "0.webp" },
      { "type": "video", "youtubeId": "cfXmieSbOEg", "thumbnail": "1.webp" },
      { "type": "image", "url": "2.webp" },
      { "type": "image", "url": "3.webp" },
      { "type": "image", "url": "4.webp" },
      { "type": "image", "url": "5.webp" },
      { "type": "image", "url": "6.webp" },
      { "type": "image", "url": "7.webp" },
      { "type": "image", "url": "8.webp" },
      { "type": "image", "url": "9.webp" },
      { "type": "image", "url": "10.webp" },
      { "type": "image", "url": "11.webp" },
      { "type": "image", "url": "12.webp" },
      { "type": "image", "url": "13.webp" },
      { "type": "image", "url": "14.webp" },
      { "type": "image", "url": "15.webp" },
      { "type": "image", "url": "16.webp" },
      { "type": "image", "url": "17.webp" },
      { "type": "image", "url": "18.webp" },
      { "type": "image", "url": "19.webp" },
      { "type": "image", "url": "20.webp" },
      { "type": "image", "url": "21.webp" },
      { "type": "image", "url": "22.webp" },
      { "type": "image", "url": "23.webp" },
      { "type": "image", "url": "24.webp" }
    ]
  },
  {
    "galleryId": "bruce-wayne-c8-stingray-w-gloss-black-sebring",
    "year": null,
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "C8 Stingray w/ Gloss Black Sebring",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SE2090E35520BK",
    "tireSizeF": "255/30R20",
    "tirePartF": null,
    "wheelSizeRear": "21\" x 12\"",
    "offsetR": "52mm",
    "wheelPartR": "E5SE2112E52520BK",
    "tireSizeR": "325/25R21",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp"]
  },
  {
    "galleryId": "c8-r-stingray",
    "year": null,
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": null,
    "vehicleTitle": "C8.R Stingray",
    "wheelStyle": "Speedway",
    "wheelFinish": "Dark Bronze",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SP1990E35520DB",
    "tireSizeF": "245/35R19",
    "tirePartF": null,
    "wheelSizeRear": "20' x 11\"",
    "offsetR": "45mm",
    "wheelPartR": null,
    "tireSizeR": "305/30R20",
    "tirePartR": null,
    "tireModel": "Michelin Pilot Sport 4S",
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp"]
  },
  {
    "galleryId": "2003-c5-corvette",
    "year": "2003",
    "submodel": "C5",
    "trim": null,
    "vehicleColor": null,
    "vehicleTitle": "2003 C5 Corvette",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "18\" x 10\"",
    "offesetF": "58mm",
    "partF": "E5DA1810E58565BK",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "19\" x 11\"",
    "offsetR": "59mm",
    "wheelPartR": "E5DA1911E59565BK",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp"]
  },
  {
    "galleryId": "2004-c5-z06",
    "year": "2004",
    "submodel": "C5",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2004 C5 Corvette Z06",
    "wheelStyle": "Daytona",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "18\" x 10\"",
    "offesetF": "58mm",
    "partF": "E5DA1810E58565BK",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "19\" x 11\"",
    "offsetR": "59mm",
    "wheelPartR": "E5DA1911E59565BK",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp"]
  },
  {
    "galleryId": "2026-c8-z06-z07-package",
    "year": "2026",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": null,
    "vehicleTitle": "2026 C8 Z06 Z07 Package",
    "wheelStyle": "Talladega",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5TA2010E25520BK",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5TA2113E20520BK",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp","29.webp","30.webp","31.webp","32.webp","33.webp","34.webp","35.webp","36.webp","37.webp","38.webp","39.webp","40.webp","41.webp","42.webp","43.webp","44.webp","45.webp","46.webp","49.webp","50.webp","51.webp","52.webp"]
  },
  {
    "galleryId": "2025-corvette-z06-black-downtown-sebring",
    "year": "2025",
    "submodel": "C8",
    "trim": "Z06",
    "vehicleColor": "Black",
    "vehicleTitle": "2025 Corvette Z06 Black Sebring",
    "wheelStyle": "Sebring",
    "wheelFinish": "Gloss Black Polished Lip",
    "wheelSizeF": "20\" x 10\"",
    "offesetF": "25mm",
    "partF": "E5SE22010E25520BKPO",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "21\" x 13\"",
    "offsetR": "20mm",
    "wheelPartR": "E5SE22113E20520BKPO",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","3.webp","4.webp","6.webp","7.webp","8.webp","9.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","27.webp","29.webp","30.webp","31.webp","33.webp","34.webp","36.webp","37.webp","38.webp","40.webp","42.webp","44.webp","45.webp","46.webp","47.webp","48.webp","49.webp"]
  },
  {
    "galleryId": "2023-c8-stingray-white-e5-speedway-gloss-black",
    "dateAdded": "2026-05-14",
    "year": "2023",
    "submodel": "C8",
    "trim": "Stingray",
    "vehicleColor": "White",
    "vehicleTitle": "2023 C8 Corvette Stingray White",
    "wheelStyle": "Speedway",
    "wheelFinish": "Gloss Black",
    "wheelSizeF": "19\" x 9\"",
    "offesetF": "35mm",
    "partF": "E5SP1990E35520BK",
    "tireSizeF": null,
    "tirePartF": null,
    "wheelSizeRear": "20\" x 11\"",
    "offsetR": "45mm",
    "wheelPartR": "E5SP2011E45520BK",
    "tireSizeR": null,
    "tirePartR": null,
    "tireModel": null,
    "images": ["0.webp","1.webp","2.webp","3.webp","4.webp","5.webp","6.webp","7.webp","8.webp","9.webp","10.webp","11.webp","12.webp","13.webp","14.webp","15.webp","16.webp","17.webp","18.webp","19.webp","20.webp","21.webp","22.webp","23.webp","24.webp","25.webp","26.webp","27.webp","28.webp","29.webp","30.webp","31.webp","32.webp"]
  }
];
